Get http://localhost:3000/hello

###

Get http://localhost:3000/
Content-Type: application/json

###

POST http://localhost:3000/login
Content-Type: application/json

{
   "username": "alyaa",
    "password": "alyazaff"
    
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "alyaa",
    "password": "alyazaff",
    "name": " Alyaa",
    "email": "zafiraa@gmail.com"
}

###

GET  http://localhost:3000/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFseWFhIiwicGFzc3dvcmQiOiJhbHlhemFmZiIsIm5hbWUiOiIgQWx5YWEiLCJlbWFpbCI6InphZmlyYWFAZ21haWwuY29tIiwiaWF0IjoxNjgxMTExNzg1LCJleHAiOjE2ODExMTUzODV9.W2TagLJ97OU2j8qD_HmNhHM9XKjGZXRdpoTj6HSD7Tk

