Get http://localhost:4000/

###

POST http://localhost:4000/register
Content-Type: application/json

{
   "username": "mirull",
    "password": "mirullencem",
    "name": " Amirul",
    "email": "yoish@gmail.com"
}

###

POST http://localhost:4000/
Content-Type: application/json

{
    "username": "mirull",
    "password": "mirullencem",
    "name": " Amirul",
    "email": "yoish@gmail.com"
}